version: "3.7"

services:

  app_proxy:
    environment:
      # The format here is: <app-id>_<docker-service-name>_1
      APP_HOST: sparkles-hello-world_server_1
      APP_PORT: 3000
    
  server:
    # image: getumbrel/community-app-store-hello-world:latest
    image: lscr.io/linuxserver/emulatorjs:latest
    user: "1000:1000"
    init: true
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Sao_Paulo
    ports:
      - 3000:3000
      - 4001:4001
      - 88:80
    volumes:
      - /mnt/data/AppData/emulatorjs/config:/config
      - /mnt/data/AppData/emulatorjs/data:/data
      - /mnt/data/ROMS/nes:/data/nes/roms
