version: "3.7"
services:

  app_proxy:
    environment:
      # The format here is: <app-id>_<docker-service-name>_1
      APP_HOST:  sparkles-emulatorjs_server_1 # ajuste o nome do serviço do emulador JS conforme necessário
      APP_PORT: 3100


  server:
    image: lscr.io/linuxserver/emulatorjs:latest
    user: "1000:1000"
    init: true
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Sao_Paulo
      - SUBFOLDER=/ # opcional
    volumes:
      - /caminho/para/seu/config:/config
      - /caminho/para/seus/dados:/data
    ports:
      - 3100:3000
      - 8100:80
      - 4001:4001 # opcional
    restart: unless-stopped
