version: "3.7"
services:

  app_proxy:
    environment:
      # The format here is: <app-id>_<docker-service-name>_1
      APP_HOST:  sparkles-emulatorjs_server_1 # ajuste o nome do serviço do emulador JS conforme necessário
      APP_PORT: 3000


  server:
    image: lscr.io/linuxserver/emulatorjs:latest
    user: "1000:1000"
    init: true
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Sao_Paulo